<?php
require __DIR__.'/config.php';require __DIR__.'/database_upgrade.php';require __DIR__.'/owner_layout.php';require __DIR__.'/customer_layout.php';try{$pdo=db();apply_database_upgrade($pdo);}catch(Throwable $e){exit('Appointments are unavailable.');}
if(!logged_in()||!in_array(user()['role'],['customer','owner'],true)){flash('Please log in to use appointments.','error');redirect('index.php?page=login');}$u=user();$owner=is_role('owner');
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$a=$_POST['action']??'';$id=(int)($_POST['id']??0);
 if($a==='book'&&!$owner){$bid=(int)$_POST['business_id'];$at=trim($_POST['appointment_at']??'');$date=DateTime::createFromFormat('Y-m-d\TH:i',$at);$q=$pdo->prepare('SELECT owner_id FROM businesses WHERE id=? AND status="approved"');$q->execute([$bid]);$businessOwner=(int)$q->fetchColumn();if(!$businessOwner||!$date||$date<=new DateTime()){flash('Choose a future appointment time for an available business.','error');redirect('index.php?page=business&id='.$bid);}$slot=$date->format('Y-m-d H:i:s');$q=$pdo->prepare("SELECT COUNT(*) FROM appointments WHERE business_id=? AND appointment_at=? AND status IN ('pending','confirmed','rescheduled')");$q->execute([$bid,$slot]);if($q->fetchColumn()){flash('That time is no longer available. Please choose another slot.','error');redirect('index.php?page=business&id='.$bid);}$pdo->prepare('INSERT INTO appointments(business_id,service_id,customer_id,appointment_at,notes) VALUES(?,?,?,?,?)')->execute([$bid,(int)$_POST['service_id']?:null,$u['id'],$slot,mb_strimwidth(trim($_POST['notes']??''),0,2000,'')]);notify_user($pdo,$businessOwner,'You have a new appointment request.','appointments.php','appointment');audit($pdo,$u['id'],'Appointment requested','Business #'.$bid);flash('Appointment request sent.');redirect('appointments.php');}
 if($a==='customer_cancel'&&!$owner){$pdo->prepare("UPDATE appointments SET status='cancelled' WHERE id=? AND customer_id=? AND status='pending'")->execute([$id,$u['id']]);flash('Appointment cancelled.');redirect('appointments.php');}
 if($owner&&$a==='owner_status'){$status=$_POST['status']??'';if(!in_array($status,['confirmed','rejected','rescheduled','completed','cancelled'],true)){exit('Invalid status.');}$q=$pdo->prepare('SELECT a.customer_id,a.business_id FROM appointments a JOIN businesses b ON b.id=a.business_id WHERE a.id=? AND b.owner_id=?');$q->execute([$id,$u['id']]);$row=$q->fetch();if(!$row){http_response_code(403);exit('Not permitted.');}$newAt=null;if($status==='rescheduled'){$d=DateTime::createFromFormat('Y-m-d\TH:i',trim($_POST['appointment_at']??''));if(!$d){flash('Choose a valid new time.','error');redirect('appointments.php');}$newAt=$d->format('Y-m-d H:i:s');}$pdo->prepare('UPDATE appointments SET status=?,appointment_at=COALESCE(?,appointment_at),owner_notes=? WHERE id=?')->execute([$status,$newAt,mb_strimwidth(trim($_POST['owner_notes']??''),0,2000,''),$id]);notify_user($pdo,(int)$row['customer_id'],'Your appointment was '.($status==='rescheduled'?'rescheduled':$status).'.','appointments.php','appointment');audit($pdo,$u['id'],'Appointment '.$status,'Appointment #'.$id);flash('Appointment updated.');redirect('appointments.php');}}
if($owner){$q=$pdo->prepare('SELECT a.*,b.name business,cu.name customer,s.name service FROM appointments a JOIN businesses b ON b.id=a.business_id JOIN users cu ON cu.id=a.customer_id LEFT JOIN services s ON s.id=a.service_id WHERE b.owner_id=? ORDER BY a.appointment_at DESC');$q->execute([$u['id']]);}else{$q=$pdo->prepare('SELECT a.*,b.name business,s.name service FROM appointments a JOIN businesses b ON b.id=a.business_id LEFT JOIN services s ON s.id=a.service_id WHERE a.customer_id=? ORDER BY a.appointment_at DESC');$q->execute([$u['id']]);}$rows=$q->fetchAll();
if($owner){$q=$pdo->prepare('SELECT id FROM businesses WHERE owner_id=? ORDER BY updated_at DESC');$q->execute([$u['id']]);$firstBusiness=(int)$q->fetchColumn();}$q=$pdo->prepare('SELECT COUNT(*) FROM messages WHERE receiver_id=? AND read_at IS NULL');$q->execute([$u['id']]);$unreadMessages=(int)$q->fetchColumn();
ob_start();
?>
<?php if($f=take_flash()):?><div class="flash <?=e($f[1])?>"><?=e($f[0])?></div><?php endif?><section class="panel"><div class="table-wrap"><table><tr><th>Business</th><?php if($owner):?><th>Customer</th><?php endif?><th>Service</th><th>Time</th><th>Status</th><th>Notes</th><th>Action</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['business'])?></td><?php if($owner):?><td><?=e($r['customer'])?></td><?php endif?><td><?=e($r['service']??'General appointment')?></td><td><?=e(date('M j, Y g:i A',strtotime($r['appointment_at'])))?></td><td><span class="status <?=e($r['status'])?>"><?=e($r['status'])?></span></td><td><?=e($r['owner_notes']?:$r['notes'])?></td><td><?php if($owner):?><form method="post" class="action-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="owner_status"><input type="hidden" name="id" value="<?=$r['id']?>"><select name="status"><option>confirmed</option><option>rejected</option><option>rescheduled</option><option>completed</option><option>cancelled</option></select><input type="datetime-local" name="appointment_at"><input name="owner_notes" placeholder="Optional note"><button class="button coral">Update</button></form><?php elseif($r['status']==='pending'):?><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="customer_cancel"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger">Cancel</button></form><?php endif?></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="7">No appointments yet.</td></tr><?php endif?></table></div></section>
<?php
$content=ob_get_clean();
if($owner)owner_page('Appointments',$content,'appointments',$firstBusiness);
customer_page('My appointments',$content,$unreadMessages);
