<?php
require __DIR__.'/config.php'; require __DIR__.'/database_upgrade.php'; require __DIR__.'/owner_layout.php'; require __DIR__.'/customer_layout.php'; try{$pdo=db();apply_database_upgrade($pdo);}catch(Throwable $e){exit('Notifications are unavailable.');}
if(!logged_in()){redirect('index.php?page=login');}$u=user();$owner=is_role('owner');
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();if(($_POST['action']??'')==='all')$pdo->prepare('UPDATE notifications SET is_read=1 WHERE user_id=?')->execute([$u['id']]);else $pdo->prepare('UPDATE notifications SET is_read=1 WHERE id=? AND user_id=?')->execute([(int)$_POST['id'],$u['id']]);redirect('notifications.php');}
$q=$pdo->prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100');$q->execute([$u['id']]);$notes=$q->fetchAll();$q=$pdo->prepare('SELECT COUNT(*) FROM messages WHERE receiver_id=? AND read_at IS NULL');$q->execute([$u['id']]);$unreadMessages=(int)$q->fetchColumn();if($owner){$q=$pdo->prepare('SELECT id FROM businesses WHERE owner_id=? ORDER BY updated_at DESC');$q->execute([$u['id']]);$firstBusiness=(int)$q->fetchColumn();}
ob_start();
?>
<?php if($f=take_flash()):?><div class="flash <?=e($f[1])?>"><?=e($f[0])?></div><?php endif?><section class="panel activity-list notification-panel"><div class="panel-intro"><div><p class="eyebrow">ACTIVITY</p><h2>Latest updates</h2></div><span><?=count($notes)?> notification<?=count($notes)===1?'':'s'?></span></div><?php foreach($notes as $n):?><article class="notification-item <?=$n['is_read']?'':'unread-note'?>"><div class="notification-dot" aria-hidden="true"></div><div class="notification-copy"><b><?=e($n['message'])?></b><small><?=e(date('M j, Y g:i A',strtotime($n['created_at'])))?></small></div><div class="notification-actions"><?php if($n['link_url']):?><a class="text-link" href="<?=e($n['link_url'])?>">Open</a><?php endif?><?php if(!$n['is_read']):?><form method="post" class="inline"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$n['id']?>"><button class="link-button">Mark read</button></form><?php endif?></div></article><?php endforeach;if(!$notes):?><div class="workspace-empty"><b>You’re all caught up.</b><p>New business activity and messages will appear here.</p></div><?php endif?></section>
<?php
$content=ob_get_clean();ob_start();?><form method="post" class="header-action"><input type="hidden" name="csrf" value="<?=csrf()?>"><button name="action" value="all" class="button light">Mark all as read</button></form><?php $headerAction=ob_get_clean();
if($owner)owner_page('Notifications',$content,'notifications',$firstBusiness,$headerAction);
customer_page('Notifications',$content,$unreadMessages,$headerAction);
