<?php
require __DIR__ . '/config.php'; require __DIR__ . '/database_upgrade.php'; require __DIR__ . '/owner_layout.php';
try{$pdo=db();apply_database_upgrade($pdo);}catch(Throwable $e){http_response_code(503);exit('The database is unavailable. Please try again later.');}
if(!is_role('owner')){flash('Business owner access is required.','error');redirect('index.php?page=login');}
$u=user();$q=$pdo->prepare('SELECT id,name FROM businesses WHERE owner_id=? ORDER BY name');$q->execute([$u['id']]);$shops=$q->fetchAll();$shopId=(int)($_GET['business']??$_POST['business_id']??($shops[0]['id']??0));
$owns=$pdo->prepare('SELECT id FROM businesses WHERE id=? AND owner_id=?');$owns->execute([$shopId,$u['id']]);if(!$owns->fetchColumn()){http_response_code(403);exit('You can only manage products for your own business.');}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$a=$_POST['action']??'';$id=(int)($_POST['id']??0);if($a==='save'){$name=trim($_POST['name']??'');if(!$name){flash('Please enter a product name.','error');redirect('products.php?business='.$shopId);}if($id){$pdo->prepare('UPDATE products SET name=?,description=?,price=?,stock=?,availability=? WHERE id=? AND business_id=?')->execute([$name,trim($_POST['description']),$_POST['price']!==''?$_POST['price']:null,$_POST['stock']!==''?$_POST['stock']:null,$_POST['availability'],$id,$shopId]);flash('Product changes saved.');}else{$pdo->prepare('INSERT INTO products(business_id,name,description,price,stock,availability)VALUES(?,?,?,?,?,?)')->execute([$shopId,$name,trim($_POST['description']),$_POST['price']!==''?$_POST['price']:null,$_POST['stock']!==''?$_POST['stock']:null,$_POST['availability']]);flash('Product added to your business.');}redirect('products.php?business='.$shopId);}if($a==='delete'){$pdo->prepare('DELETE FROM products WHERE id=? AND business_id=?')->execute([$id,$shopId]);flash('Product removed.');redirect('products.php?business='.$shopId);}}
$edit=null;if(isset($_GET['edit'])){$q=$pdo->prepare('SELECT * FROM products WHERE id=? AND business_id=?');$q->execute([(int)$_GET['edit'],$shopId]);$edit=$q->fetch();}$q=$pdo->prepare('SELECT * FROM products WHERE business_id=? ORDER BY updated_at DESC');$q->execute([$shopId]);$rows=$q->fetchAll();$firstBusiness=(int)($shops[0]['id']??0);
ob_start();
?>
<?php if($f=take_flash()):?><div class="flash <?=e($f[1])?>"><?=e($f[0])?></div><?php endif?>
<section class="panel"><div class="panel-title"><div><h2><?=$edit?'Edit product':'Add product'?></h2><p>Manage products customers see for this business.</p></div><a class="button light" href="owner.php?edit=<?=$shopId?>">Back to business</a></div><form method="post" class="registration-form wide"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save"><input type="hidden" name="business_id" value="<?=$shopId?>"><input type="hidden" name="id" value="<?=$edit['id']??''?>"><div class="form-grid"><label>Product name<input required name="name" value="<?=e($edit['name']??'')?>"></label><label>Price (PHP)<input type="number" step=".01" min="0" name="price" value="<?=e($edit['price']??'')?>"></label><label>Stock<input type="number" min="0" name="stock" value="<?=e($edit['stock']??'')?>"></label><label>Availability<select name="availability"><option value="available">Available</option><option value="unavailable" <?=($edit['availability']??'')==='unavailable'?'selected':''?>>Unavailable</option></select></label></div><label>Description<textarea name="description"><?=e($edit['description']??'')?></textarea></label><button class="button coral"><?=$edit?'Save changes':'Add product'?></button></form></section>
<section class="panel"><h2>Products</h2><div class="table-wrap"><table><tr><th>Product</th><th>Price</th><th>Stock</th><th>Availability</th><th>Actions</th></tr><?php foreach($rows as $r):?><tr><td><b><?=e($r['name'])?></b><small><?=e($r['description'])?></small></td><td><?=$r['price']===null?'—':'₱'.number_format((float)$r['price'],2)?></td><td><?=$r['stock']??'—'?></td><td><span class="status <?=e($r['availability'])?>"><?=e($r['availability'])?></span></td><td><a class="link-button" href="?business=<?=$shopId?>&edit=<?=$r['id']?>">Edit</a><form method="post" class="inline"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="business_id" value="<?=$shopId?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button name="action" value="delete" class="danger" onclick="return confirm('Delete this product?')">Delete</button></form></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="5">No products yet. Add your first product above.</td></tr><?php endif?></table></div></section>
<?php
$content=ob_get_clean();
ob_start();
?><form method="get"><select name="business" onchange="this.form.submit()"><?php foreach($shops as $s):?><option value="<?=$s['id']?>" <?=$s['id']==$shopId?'selected':''?>><?=e($s['name'])?></option><?php endforeach?></select></form><?php
$headerAction=ob_get_clean();
owner_page('Products',$content,'products',$firstBusiness,$headerAction);
