document.addEventListener('DOMContentLoaded',()=>{
  if(location.pathname.endsWith('/owner.php')){const manage=document.querySelector('a[href^="owner.php?edit="]')?.getAttribute('href');document.querySelectorAll('#owner-links a').forEach(link=>{const label=link.textContent.trim();if(label.includes('Services')&&manage)link.href=manage+'#services';if(label.includes('Reviews'))link.href='owner_reviews.php';});}
  document.querySelectorAll('.menu-toggle').forEach(button=>button.onclick=()=>{const menu=document.getElementById(button.getAttribute('aria-controls'));const open=menu.classList.toggle('is-open');button.setAttribute('aria-expanded',String(open));});
  document.querySelectorAll('.flash').forEach(el=>{const close=document.createElement('button');close.type='button';close.className='flash-close';close.setAttribute('aria-label','Close notification');close.textContent='×';close.onclick=()=>el.remove();el.append(close);setTimeout(()=>el.remove(),6500);});
  document.querySelectorAll('[data-geolocate]').forEach(button=>button.onclick=()=>{const form=button.closest('form'),lat=form?.querySelector('input[name="latitude"]'),lng=form?.querySelector('input[name="longitude"]'),result=button.parentElement.querySelector('[data-location-status]');if(!navigator.geolocation){result.textContent='Location is not available in this browser.';return;}button.disabled=true;button.textContent='Detecting location…';navigator.geolocation.getCurrentPosition(pos=>{lat.value=pos.coords.latitude.toFixed(7);lng.value=pos.coords.longitude.toFixed(7);result.textContent='Location captured. Save the profile to keep it.';button.textContent='Location captured';},()=>{result.textContent='We could not access your location. Check permission and try again.';button.disabled=false;button.textContent='Try again';},{enableHighAccuracy:true,timeout:10000});});
});
document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('[data-image-preview]').forEach(input=>input.onchange=()=>{const preview=input.parentElement.querySelector('.image-preview'),file=input.files?.[0];if(!preview||!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){alert('Choose a JPG, PNG, or WebP image up to 5 MB.');input.value='';preview.hidden=true;return;}preview.src=URL.createObjectURL(file);preview.hidden=false;}));
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-hours-editor]').forEach(editor=>editor.querySelectorAll('.hours-status input').forEach(box=>{const row=box.closest('.hours-row'),times=row.querySelectorAll('input[type=time]'),label=row.querySelector('.hours-status span'),action=row.querySelector('.hours-action');const sync=()=>{times.forEach(input=>input.disabled=box.checked);label.textContent=box.checked?'Closed':'Open';action.textContent=box.checked?'Closed':'Available';};box.addEventListener('change',sync);sync();}));document.querySelectorAll('[data-clear-filters]').forEach(button=>button.addEventListener('click',()=>location.href='index.php?page=directory'));document.querySelectorAll('[data-near-me]').forEach(button=>button.addEventListener('click',()=>{if(!navigator.geolocation){alert('Location is not supported in this browser.');return;}button.disabled=true;button.textContent='Finding you…';navigator.geolocation.getCurrentPosition(position=>{const form=button.closest('form');form.querySelector('[name=lat]').value=position.coords.latitude.toFixed(6);form.querySelector('[name=lng]').value=position.coords.longitude.toFixed(6);form.querySelector('[name=sort]').value='nearest';form.submit();},()=>{button.disabled=false;button.textContent='📍 Near me';alert('Location was not shared. You can still search by area or barangay.');},{enableHighAccuracy:true,timeout:10000});}));});
document.addEventListener('DOMContentLoaded',()=>{const toggle=document.querySelector('.nav-toggle'),nav=document.querySelector('#site-navigation');if(toggle&&nav)toggle.addEventListener('click',()=>{const open=nav.classList.toggle('is-open');toggle.setAttribute('aria-expanded',String(open));});});
document.addEventListener('DOMContentLoaded',()=>{const button=document.querySelector('.directory-filters .filter-actions .coral');if(button&&button.textContent.trim()==='Apply filters')button.textContent='Search';});
